package pojo;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Continentes generated by hbm2java
 */
@Entity
@Table(name="contienentes")
public class Continente implements java.io.Serializable {

	@Id
	@Column(name="id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	
	private String nombre;
	private int poblacion;
	@OneToMany(targetEntity=Pais.class)
	@JoinColumn(name="continente_id")
	private Set paises = new HashSet(0);

	public Continente() {
	}

	public Continente(int id, String nombre, int poblacion) {
		this.id = id;
		this.nombre = nombre;
		this.poblacion = poblacion;
	}

	public Continente(int id, String nombre, int poblacion, Set paiseses) {
		this.id = id;
		this.nombre = nombre;
		this.poblacion = poblacion;
		this.paises = paiseses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(int poblacion) {
		this.poblacion = poblacion;
	}

	public Set getPaiseses() {
		return this.paises;
	}

	public void setPaiseses(Set paiseses) {
		this.paises = paiseses;
	}

}
